# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
    ]
