# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.FileField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='good',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
