# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170221_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.FileField(blank=True, upload_to='static/main/img/'),
        ),
    ]
