# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170228_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.FileField(blank=True, upload_to='img/%Y/%m/%d'),
        ),
    ]
