# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170302_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.FileField(upload_to='media/%Y/%m/%d'),
        ),
    ]
