# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170302_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
