# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20170305_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='good',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
