# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170307_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.TextField(),
        ),
    ]
