# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20170307_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='img/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='good',
            name='image',
        ),
        migrations.AddField(
            model_name='good',
            name='images',
            field=models.ManyToManyField(to='main.Image'),
        ),
    ]
