# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20170320_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='images',
            field=models.ManyToManyField(blank=True, to='main.Image'),
        ),
    ]
