# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20170328_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='images',
            field=models.ManyToManyField(to='main.Image'),
        ),
    ]
